/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    posts: Post;
    publications: Publication;
    events: Event;
    team: Team;
    partners: Partner;
    programmes: Programme;
    'gallery-items': GalleryItem;
    testimonials: Testimonial;
    categories: Category;
    tags: Tag;
    subscribers: Subscriber;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    publications: PublicationsSelect<false> | PublicationsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    programmes: ProgrammesSelect<false> | ProgrammesSelect<true>;
    'gallery-items': GalleryItemsSelect<false> | GalleryItemsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'partners-settings': PartnersSetting;
    'award-settings': AwardSetting;
    'footer-settings': FooterSetting;
    'seo-settings': SeoSetting;
    'social-media-settings': SocialMediaSetting;
    'contact-settings': ContactSetting;
    'general-settings': GeneralSetting;
    'home-page-settings': HomePageSetting;
    'about-us-page-settings': AboutUsPageSetting;
    'programme-page-settings': ProgrammePageSetting;
    'event-page-settings': EventPageSetting;
    'media-page-settings': MediaPageSetting;
    'reports-settings': ReportsSetting;
    'contact-us-page-settings': ContactUsPageSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'partners-settings': PartnersSettingsSelect<false> | PartnersSettingsSelect<true>;
    'award-settings': AwardSettingsSelect<false> | AwardSettingsSelect<true>;
    'footer-settings': FooterSettingsSelect<false> | FooterSettingsSelect<true>;
    'seo-settings': SeoSettingsSelect<false> | SeoSettingsSelect<true>;
    'social-media-settings': SocialMediaSettingsSelect<false> | SocialMediaSettingsSelect<true>;
    'contact-settings': ContactSettingsSelect<false> | ContactSettingsSelect<true>;
    'general-settings': GeneralSettingsSelect<false> | GeneralSettingsSelect<true>;
    'home-page-settings': HomePageSettingsSelect<false> | HomePageSettingsSelect<true>;
    'about-us-page-settings': AboutUsPageSettingsSelect<false> | AboutUsPageSettingsSelect<true>;
    'programme-page-settings': ProgrammePageSettingsSelect<false> | ProgrammePageSettingsSelect<true>;
    'event-page-settings': EventPageSettingsSelect<false> | EventPageSettingsSelect<true>;
    'media-page-settings': MediaPageSettingsSelect<false> | MediaPageSettingsSelect<true>;
    'reports-settings': ReportsSettingsSelect<false> | ReportsSettingsSelect<true>;
    'contact-us-page-settings': ContactUsPageSettingsSelect<false> | ContactUsPageSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Manage admin users and their permissions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Super Admin: Full access | Admin: Manage content | Editor: Create/edit content only
   */
  role: 'super-admin' | 'admin' | 'editor';
  avatar?: (number | null) | Media;
  /**
   * Inactive users cannot log in
   */
  isActive?: boolean | null;
  /**
   * Last login timestamp
   */
  lastLogin?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Blog posts and activity reports
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  featuredImage: number | Media;
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Add images or YouTube videos to this post
   */
  mediaGallery?:
    | {
        type: 'image' | 'youtube';
        image?: (number | null) | Media;
        /**
         * The ID from the YouTube URL (e.g., dQw4w9WgXcQ)
         */
        youtubeId?: string | null;
        youtubeTitle?: string | null;
        /**
         * Optional caption for this media item
         */
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  category: number | Category;
  tags?: (number | Tag)[] | null;
  author?: (number | null) | User;
  status: 'draft' | 'published';
  /**
   * Top-level website menu where this content belongs.
   */
  menuSection: 'about-us' | 'media' | 'report';
  /**
   * Specific submenu destination for display/routing.
   */
  subMenu:
    | 'who-we-are'
    | 'our-strategy'
    | 'our-team'
    | 'blog'
    | 'press-statement'
    | 'gallery-photo'
    | 'gallery-video'
    | 'publication'
    | 'annual-report'
    | 'project-report'
    | 'strategic-plan';
  publishedAt?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Blog post categories
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  /**
   * Hex color code (e.g., #28005b)
   */
  color?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Tags for posts and publications
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Research papers, reports, and downloadable resources
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications".
 */
export interface Publication {
  id: number;
  title: string;
  slug: string;
  coverImage: number | Media;
  file: number | Media;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  excerpt?: string | null;
  category: 'research' | 'report' | 'policy-brief' | 'factsheet' | 'manual' | 'other';
  menuSection: 'report';
  /**
   * Submenu destination under Report.
   */
  subMenu: 'publication' | 'annual-report' | 'project-report' | 'strategic-plan';
  year: number;
  author?: string | null;
  region?: string | null;
  pages?: number | null;
  accentColor?: ('blue' | 'emerald' | 'purple' | 'amber') | null;
  downloadCount?: number | null;
  isFeatured?: boolean | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Upcoming and past events
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  slug: string;
  featuredImage: number | Media;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  excerpt?: string | null;
  location: string;
  venue?: string | null;
  startDate: string;
  endDate?: string | null;
  maxAttendees?: number | null;
  registrationLink?: string | null;
  status: 'upcoming' | 'ongoing' | 'completed' | 'cancelled';
  isFeatured?: boolean | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Team members, board of trustees, and advisors
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  name: string;
  position: string;
  photo?: (number | null) | Media;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  shortBio?: string | null;
  email?: string | null;
  category: 'board' | 'staff' | 'advisors' | 'volunteers';
  socialLinks?: {
    linkedin?: string | null;
    twitter?: string | null;
    email?: string | null;
  };
  order?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Partners and collaborating organizations
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  logo: number | Media;
  website?: string | null;
  description?: string | null;
  category?: ('funding' | 'implementing' | 'strategic' | 'network') | null;
  order?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Programs and initiatives
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programmes".
 */
export interface Programme {
  id: number;
  title: string;
  slug: string;
  featuredImage: number | Media;
  /**
   * Lucide icon name (e.g., "users", "heart", "globe")
   */
  icon?: string | null;
  shortDescription: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  objectives?:
    | {
        objective: string;
        id?: string | null;
      }[]
    | null;
  achievements?:
    | {
        title: string;
        description?: string | null;
        /**
         * e.g., "5000+ youth trained"
         */
        metric?: string | null;
        id?: string | null;
      }[]
    | null;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  status: 'active' | 'completed' | 'upcoming';
  order?: number | null;
  isFeatured?: boolean | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Photo and video entries shown on the gallery page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-items".
 */
export interface GalleryItem {
  id: number;
  title: string;
  mediaType: 'photo' | 'video';
  category: string;
  /**
   * Required for photo items.
   */
  image?: (number | null) | Media;
  /**
   * Required for video items. Example: xvQ_AXIQbPM
   */
  youtubeId?: string | null;
  status: 'published' | 'draft';
  order?: number | null;
  isFeatured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Testimonials displayed on the testimonials page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  role: string;
  quote: string;
  image?: (number | null) | Media;
  rating?: number | null;
  status: 'published' | 'draft';
  order?: number | null;
  isFeatured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Newsletter subscribers
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  email: string;
  name?: string | null;
  status: 'active' | 'unsubscribed' | 'bounced';
  subscribedAt?: string | null;
  unsubscribeToken?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'publications';
        value: number | Publication;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'programmes';
        value: number | Programme;
      } | null)
    | ({
        relationTo: 'gallery-items';
        value: number | GalleryItem;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  avatar?: T;
  isActive?: T;
  lastLogin?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  featuredImage?: T;
  excerpt?: T;
  content?: T;
  mediaGallery?:
    | T
    | {
        type?: T;
        image?: T;
        youtubeId?: T;
        youtubeTitle?: T;
        caption?: T;
        id?: T;
      };
  category?: T;
  tags?: T;
  author?: T;
  status?: T;
  menuSection?: T;
  subMenu?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications_select".
 */
export interface PublicationsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  coverImage?: T;
  file?: T;
  description?: T;
  excerpt?: T;
  category?: T;
  menuSection?: T;
  subMenu?: T;
  year?: T;
  author?: T;
  region?: T;
  pages?: T;
  accentColor?: T;
  downloadCount?: T;
  isFeatured?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  featuredImage?: T;
  description?: T;
  excerpt?: T;
  location?: T;
  venue?: T;
  startDate?: T;
  endDate?: T;
  maxAttendees?: T;
  registrationLink?: T;
  status?: T;
  isFeatured?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  position?: T;
  photo?: T;
  bio?: T;
  shortBio?: T;
  email?: T;
  category?: T;
  socialLinks?:
    | T
    | {
        linkedin?: T;
        twitter?: T;
        email?: T;
      };
  order?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  website?: T;
  description?: T;
  category?: T;
  order?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programmes_select".
 */
export interface ProgrammesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  featuredImage?: T;
  icon?: T;
  shortDescription?: T;
  content?: T;
  objectives?:
    | T
    | {
        objective?: T;
        id?: T;
      };
  achievements?:
    | T
    | {
        title?: T;
        description?: T;
        metric?: T;
        id?: T;
      };
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  status?: T;
  order?: T;
  isFeatured?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-items_select".
 */
export interface GalleryItemsSelect<T extends boolean = true> {
  title?: T;
  mediaType?: T;
  category?: T;
  image?: T;
  youtubeId?: T;
  status?: T;
  order?: T;
  isFeatured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  quote?: T;
  image?: T;
  rating?: T;
  status?: T;
  order?: T;
  isFeatured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  color?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  status?: T;
  subscribedAt?: T;
  unsubscribeToken?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  siteTagline?: string | null;
  logo?: (number | null) | Media;
  logoAlt?: (number | null) | Media;
  favicon?: (number | null) | Media;
  /**
   * Small text shown above the main title
   */
  heroSlogan?: string | null;
  /**
   * The large headline text
   */
  heroMainTitle?: string | null;
  /**
   * Add background images and descriptions for the hero slider
   */
  heroSlides?:
    | {
        image: number | Media;
        /**
         * Brief description shown on this slide
         */
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Phrases that appear with typewriter effect: "We [phrase]"
   */
  typewriterPhrases?:
    | {
        phrase: string;
        id?: string | null;
      }[]
    | null;
  heroCta?: {
    primaryText?: string | null;
    primaryLink?: string | null;
    secondaryText?: string | null;
    secondaryLink?: string | null;
  };
  contactEmail: string;
  phone?: string | null;
  phoneAlt?: string | null;
  address?: string | null;
  socialLinks?: {
    facebook?: string | null;
    twitter?: string | null;
    instagram?: string | null;
    youtube?: string | null;
    linkedin?: string | null;
  };
  /**
   * Statistics displayed on the homepage
   */
  impactStats?:
    | {
        label: string;
        value: string;
        /**
         * e.g., "+", "K", etc.
         */
        suffix?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * YouTube video displayed on homepage
   */
  featuredVideo?: {
    /**
     * The ID from the YouTube URL (e.g., xvQ_AXIQbPM)
     */
    youtubeId?: string | null;
    title?: string | null;
    thumbnail?: (number | null) | Media;
  };
  aboutTitle?: string | null;
  /**
   * Main about section content
   */
  aboutDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Key focus areas shown as bullet points
   */
  aboutHighlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  aboutVideo?: {
    youtubeId?: string | null;
    title?: string | null;
  };
  aboutImages?: {
    mainImage?: (number | null) | Media;
    secondaryImage?: (number | null) | Media;
  };
  /**
   * Displayed in the stats card
   */
  yearsOfImpact?: string | null;
  mission?: string | null;
  vision?: string | null;
  coreValues?:
    | {
        value: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  footerText?: string | null;
  copyrightText?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  menuStructure?: {
    aboutUsSubmenu?:
      | {
          title: string;
          slug: string;
          id?: string | null;
        }[]
      | null;
    mediaSubmenu?:
      | {
          title: string;
          slug: string;
          id?: string | null;
        }[]
      | null;
    reportSubmenu?:
      | {
          title: string;
          slug: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Existing annual reports as editable placeholders in admin.
   */
  annualReportPlaceholders?:
    | {
        title: string;
        year: number;
        fileUrl: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners-settings".
 */
export interface PartnersSetting {
  id: number;
  heading?: string | null;
  subheading?: string | null;
  description?: string | null;
  ctaText?: string | null;
  ctaLinkLabel?: string | null;
  items?:
    | {
        name: string;
        description?: string | null;
        logo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "award-settings".
 */
export interface AwardSetting {
  id: number;
  awards?:
    | {
        title: string;
        year: number;
        issuer?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-settings".
 */
export interface FooterSetting {
  id: number;
  footerText?: string | null;
  copyrightText?: string | null;
  quickLinksTitle?: string | null;
  programmesTitle?: string | null;
  contactTitle?: string | null;
  developedByText?: string | null;
  privacyLabel?: string | null;
  termsLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-settings".
 */
export interface SeoSetting {
  id: number;
  metaTitle?: string | null;
  metaDescription?: string | null;
  ogImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-media-settings".
 */
export interface SocialMediaSetting {
  id: number;
  facebook?: string | null;
  twitter?: string | null;
  instagram?: string | null;
  youtube?: string | null;
  linkedin?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-settings".
 */
export interface ContactSetting {
  id: number;
  contactEmail?: string | null;
  phone?: string | null;
  phoneAlt?: string | null;
  address?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "general-settings".
 */
export interface GeneralSetting {
  id: number;
  siteName?: string | null;
  siteTagline?: string | null;
  logo?: (number | null) | Media;
  logoAlt?: string | null;
  favicon?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page-settings".
 */
export interface HomePageSetting {
  id: number;
  /**
   * The large headline text
   */
  heroMainTitle?: string | null;
  /**
   * Background images and descriptions for the hero slider
   */
  heroSlides?:
    | {
        image?: (number | null) | Media;
        /**
         * Brief text shown on this slide
         */
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Phrases after "We" with typewriter effect. Add as many as you want.
   */
  typewriterPhrases?:
    | {
        phrase: string;
        id?: string | null;
      }[]
    | null;
  heroCta?: {
    primaryText?: string | null;
    primaryLink?: string | null;
    secondaryText?: string | null;
    secondaryLink?: string | null;
  };
  /**
   * Small label above the heading (e.g. "Our Presence")
   */
  impactBadge?: string | null;
  /**
   * Main heading e.g. "Creating Lasting Impact"
   */
  impactHeading?: string | null;
  impactDescription?: string | null;
  /**
   * Background image for the impact section
   */
  impactImage?: (number | null) | Media;
  /**
   * Small badge items below description (e.g. "Recognized by national bodies")
   */
  impactHighlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Stat cards like "5000+ Youth Reached Directly"
   */
  impactStats?:
    | {
        /**
         * Numeric value (e.g. 5000)
         */
        value: number;
        /**
         * Suffix after number (e.g. "+")
         */
        suffix?: string | null;
        /**
         * Stat label (e.g. "Youth Reached Directly")
         */
        label: string;
        /**
         * Short extra text (e.g. "Through our programs")
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  aboutTitle?: string | null;
  aboutParagraph1?: string | null;
  aboutParagraph2?: string | null;
  aboutHighlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  aboutMission?: string | null;
  aboutVision?: string | null;
  aboutYearsOfImpact?: string | null;
  aboutMainImage?: (number | null) | Media;
  aboutSecondaryImage?: (number | null) | Media;
  aboutVideoId?: string | null;
  aboutVideoTitle?: string | null;
  focusBadge?: string | null;
  focusHeading?: string | null;
  focusDescription?: string | null;
  focusBackgroundImage?: (number | null) | Media;
  focusAreas?:
    | {
        title: string;
        description: string;
        icon?:
          | (
              | 'Users'
              | 'Shield'
              | 'AlertTriangle'
              | 'Scale'
              | 'Leaf'
              | 'BookOpen'
              | 'Target'
              | 'Heart'
              | 'Globe'
              | 'Megaphone'
            )
          | null;
        link?: string | null;
        gradient?:
          | (
              | 'from-violet-600 via-purple-600 to-indigo-700'
              | 'from-blue-600 via-indigo-600 to-blue-800'
              | 'from-orange-500 via-red-500 to-rose-600'
              | 'from-emerald-600 via-teal-600 to-cyan-700'
              | 'from-green-600 via-emerald-600 to-teal-700'
              | 'from-amber-500 via-yellow-500 to-orange-500'
            )
          | null;
        id?: string | null;
      }[]
    | null;
  approachBadge?: string | null;
  approachHeading?: string | null;
  approachDescription?: string | null;
  approachPillars?:
    | {
        title: string;
        description: string;
        icon?:
          | ('Target' | 'GraduationCap' | 'Megaphone' | 'Handshake' | 'Radio' | 'Shield' | 'Users' | 'BookOpen')
          | null;
        color?:
          | (
              | 'from-blue-500 to-cyan-500'
              | 'from-violet-500 to-purple-500'
              | 'from-amber-500 to-orange-500'
              | 'from-emerald-500 to-green-500'
              | 'from-rose-500 to-pink-500'
            )
          | null;
        id?: string | null;
      }[]
    | null;
  initiativesBadge?: string | null;
  initiativesHeading?: string | null;
  initiativesDescription?: string | null;
  initiatives?:
    | {
        title: string;
        description: string;
        badge?: string | null;
        image?: (number | null) | Media;
        link?: string | null;
        icon?: ('Users' | 'Globe' | 'Shield' | 'Target' | 'Megaphone' | 'Heart') | null;
        color?:
          | (
              | 'from-blue-600 to-indigo-600'
              | 'from-emerald-600 to-teal-600'
              | 'from-purple-600 to-fuchsia-600'
              | 'from-amber-500 to-orange-500'
            )
          | null;
        id?: string | null;
      }[]
    | null;
  videoBadge?: string | null;
  videoHeading?: string | null;
  videoDescription?: string | null;
  videos?:
    | {
        /**
         * YouTube video ID (the part after v= in the URL)
         */
        youtubeId: string;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  awardsHeading?: string | null;
  awardsDescription?: string | null;
  awardsBackgroundImage?: (number | null) | Media;
  awards?:
    | {
        title: string;
        organization: string;
        year: string;
        description?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  newsletterHeading?: string | null;
  newsletterDescription?: string | null;
  newsletterButtonText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-us-page-settings".
 */
export interface AboutUsPageSetting {
  id: number;
  storyParagraph1?: string | null;
  storyParagraph2?: string | null;
  storyParagraph3?: string | null;
  milestones?:
    | {
        year: string;
        event: string;
        id?: string | null;
      }[]
    | null;
  storyImage1?: (number | null) | Media;
  storyImage2?: (number | null) | Media;
  storyImage3?: (number | null) | Media;
  storyImage4?: (number | null) | Media;
  vision?: string | null;
  mission?: string | null;
  coreValues?:
    | {
        title: string;
        description: string;
        icon?: ('Shield' | 'Users' | 'Lightbulb' | 'Handshake' | 'Heart' | 'UserCheck') | null;
        id?: string | null;
      }[]
    | null;
  strategyPeriod?: string | null;
  strategicPillars?:
    | {
        title: string;
        icon?: ('GraduationCap' | 'Scale' | 'Leaf' | 'Building2' | 'HeartHandshake') | null;
        gradient?:
          | (
              | 'from-blue-500 to-cyan-400'
              | 'from-emerald-500 to-green-400'
              | 'from-amber-500 to-yellow-400'
              | 'from-violet-500 to-purple-400'
              | 'from-rose-500 to-pink-400'
            )
          | null;
        id?: string | null;
      }[]
    | null;
  uniqueIntro?: string | null;
  uniquePoints?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  teamHeading?: string | null;
  teamDescription?: string | null;
  boardHeading?: string | null;
  boardDescription?: string | null;
  aboutAwards?:
    | {
        title: string;
        organization: string;
        year: string;
        id?: string | null;
      }[]
    | null;
  ctaHeading?: string | null;
  ctaDescription?: string | null;
  headOfficeAddress?: string | null;
  headOfficeCity?: string | null;
  headOfficePhone?: string | null;
  regionOfficeAddress?: string | null;
  regionOfficeCity?: string | null;
  regionOfficeEmail?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programme-page-settings".
 */
export interface ProgrammePageSetting {
  id: number;
  overviewBadge?: string | null;
  overviewHeading?: string | null;
  ctaBadge?: string | null;
  ctaHeading?: string | null;
  ctaDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-page-settings".
 */
export interface EventPageSetting {
  id: number;
  pastHeading?: string | null;
  pastDescription?: string | null;
  ongoingHeading?: string | null;
  ongoingDescription?: string | null;
  upcomingHeading?: string | null;
  upcomingDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-page-settings".
 */
export interface MediaPageSetting {
  id: number;
  /**
   * Internal note for editors (not shown on frontend)
   */
  blogNote?: string | null;
  /**
   * Internal note for editors (not shown on frontend)
   */
  pressNote?: string | null;
  testimonialsSectionHeading?: string | null;
  testimonialsSectionDescription?: string | null;
  testimonialsCtaHeading?: string | null;
  testimonialsCtaDescription?: string | null;
  testimonialsCtaButtonText?: string | null;
  photoTabTitle?: string | null;
  videoTabTitle?: string | null;
  youtubeChannelUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports-settings".
 */
export interface ReportsSetting {
  id: number;
  annualSectionHeading?: string | null;
  annualSectionDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-us-page-settings".
 */
export interface ContactUsPageSetting {
  id: number;
  officeHours?: string | null;
  website?: string | null;
  /**
   * Add your office locations
   */
  offices?:
    | {
        title: string;
        address: string;
        phone?: string | null;
        id?: string | null;
      }[]
    | null;
  mapHeading?: string | null;
  mapAddress?: string | null;
  /**
   * Google Maps directions link
   */
  mapLink?: string | null;
  /**
   * Background image for the map/directions section
   */
  mapBackgroundImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteTagline?: T;
  logo?: T;
  logoAlt?: T;
  favicon?: T;
  heroSlogan?: T;
  heroMainTitle?: T;
  heroSlides?:
    | T
    | {
        image?: T;
        description?: T;
        id?: T;
      };
  typewriterPhrases?:
    | T
    | {
        phrase?: T;
        id?: T;
      };
  heroCta?:
    | T
    | {
        primaryText?: T;
        primaryLink?: T;
        secondaryText?: T;
        secondaryLink?: T;
      };
  contactEmail?: T;
  phone?: T;
  phoneAlt?: T;
  address?: T;
  socialLinks?:
    | T
    | {
        facebook?: T;
        twitter?: T;
        instagram?: T;
        youtube?: T;
        linkedin?: T;
      };
  impactStats?:
    | T
    | {
        label?: T;
        value?: T;
        suffix?: T;
        id?: T;
      };
  featuredVideo?:
    | T
    | {
        youtubeId?: T;
        title?: T;
        thumbnail?: T;
      };
  aboutTitle?: T;
  aboutDescription?: T;
  aboutHighlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  aboutVideo?:
    | T
    | {
        youtubeId?: T;
        title?: T;
      };
  aboutImages?:
    | T
    | {
        mainImage?: T;
        secondaryImage?: T;
      };
  yearsOfImpact?: T;
  mission?: T;
  vision?: T;
  coreValues?:
    | T
    | {
        value?: T;
        description?: T;
        id?: T;
      };
  footerText?: T;
  copyrightText?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  menuStructure?:
    | T
    | {
        aboutUsSubmenu?:
          | T
          | {
              title?: T;
              slug?: T;
              id?: T;
            };
        mediaSubmenu?:
          | T
          | {
              title?: T;
              slug?: T;
              id?: T;
            };
        reportSubmenu?:
          | T
          | {
              title?: T;
              slug?: T;
              id?: T;
            };
      };
  annualReportPlaceholders?:
    | T
    | {
        title?: T;
        year?: T;
        fileUrl?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners-settings_select".
 */
export interface PartnersSettingsSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  description?: T;
  ctaText?: T;
  ctaLinkLabel?: T;
  items?:
    | T
    | {
        name?: T;
        description?: T;
        logo?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "award-settings_select".
 */
export interface AwardSettingsSelect<T extends boolean = true> {
  awards?:
    | T
    | {
        title?: T;
        year?: T;
        issuer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-settings_select".
 */
export interface FooterSettingsSelect<T extends boolean = true> {
  footerText?: T;
  copyrightText?: T;
  quickLinksTitle?: T;
  programmesTitle?: T;
  contactTitle?: T;
  developedByText?: T;
  privacyLabel?: T;
  termsLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-settings_select".
 */
export interface SeoSettingsSelect<T extends boolean = true> {
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-media-settings_select".
 */
export interface SocialMediaSettingsSelect<T extends boolean = true> {
  facebook?: T;
  twitter?: T;
  instagram?: T;
  youtube?: T;
  linkedin?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-settings_select".
 */
export interface ContactSettingsSelect<T extends boolean = true> {
  contactEmail?: T;
  phone?: T;
  phoneAlt?: T;
  address?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "general-settings_select".
 */
export interface GeneralSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteTagline?: T;
  logo?: T;
  logoAlt?: T;
  favicon?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page-settings_select".
 */
export interface HomePageSettingsSelect<T extends boolean = true> {
  heroMainTitle?: T;
  heroSlides?:
    | T
    | {
        image?: T;
        description?: T;
        id?: T;
      };
  typewriterPhrases?:
    | T
    | {
        phrase?: T;
        id?: T;
      };
  heroCta?:
    | T
    | {
        primaryText?: T;
        primaryLink?: T;
        secondaryText?: T;
        secondaryLink?: T;
      };
  impactBadge?: T;
  impactHeading?: T;
  impactDescription?: T;
  impactImage?: T;
  impactHighlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  impactStats?:
    | T
    | {
        value?: T;
        suffix?: T;
        label?: T;
        description?: T;
        id?: T;
      };
  aboutTitle?: T;
  aboutParagraph1?: T;
  aboutParagraph2?: T;
  aboutHighlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  aboutMission?: T;
  aboutVision?: T;
  aboutYearsOfImpact?: T;
  aboutMainImage?: T;
  aboutSecondaryImage?: T;
  aboutVideoId?: T;
  aboutVideoTitle?: T;
  focusBadge?: T;
  focusHeading?: T;
  focusDescription?: T;
  focusBackgroundImage?: T;
  focusAreas?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        link?: T;
        gradient?: T;
        id?: T;
      };
  approachBadge?: T;
  approachHeading?: T;
  approachDescription?: T;
  approachPillars?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        color?: T;
        id?: T;
      };
  initiativesBadge?: T;
  initiativesHeading?: T;
  initiativesDescription?: T;
  initiatives?:
    | T
    | {
        title?: T;
        description?: T;
        badge?: T;
        image?: T;
        link?: T;
        icon?: T;
        color?: T;
        id?: T;
      };
  videoBadge?: T;
  videoHeading?: T;
  videoDescription?: T;
  videos?:
    | T
    | {
        youtubeId?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  awardsHeading?: T;
  awardsDescription?: T;
  awardsBackgroundImage?: T;
  awards?:
    | T
    | {
        title?: T;
        organization?: T;
        year?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  newsletterHeading?: T;
  newsletterDescription?: T;
  newsletterButtonText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-us-page-settings_select".
 */
export interface AboutUsPageSettingsSelect<T extends boolean = true> {
  storyParagraph1?: T;
  storyParagraph2?: T;
  storyParagraph3?: T;
  milestones?:
    | T
    | {
        year?: T;
        event?: T;
        id?: T;
      };
  storyImage1?: T;
  storyImage2?: T;
  storyImage3?: T;
  storyImage4?: T;
  vision?: T;
  mission?: T;
  coreValues?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  strategyPeriod?: T;
  strategicPillars?:
    | T
    | {
        title?: T;
        icon?: T;
        gradient?: T;
        id?: T;
      };
  uniqueIntro?: T;
  uniquePoints?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  teamHeading?: T;
  teamDescription?: T;
  boardHeading?: T;
  boardDescription?: T;
  aboutAwards?:
    | T
    | {
        title?: T;
        organization?: T;
        year?: T;
        id?: T;
      };
  ctaHeading?: T;
  ctaDescription?: T;
  headOfficeAddress?: T;
  headOfficeCity?: T;
  headOfficePhone?: T;
  regionOfficeAddress?: T;
  regionOfficeCity?: T;
  regionOfficeEmail?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programme-page-settings_select".
 */
export interface ProgrammePageSettingsSelect<T extends boolean = true> {
  overviewBadge?: T;
  overviewHeading?: T;
  ctaBadge?: T;
  ctaHeading?: T;
  ctaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-page-settings_select".
 */
export interface EventPageSettingsSelect<T extends boolean = true> {
  pastHeading?: T;
  pastDescription?: T;
  ongoingHeading?: T;
  ongoingDescription?: T;
  upcomingHeading?: T;
  upcomingDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-page-settings_select".
 */
export interface MediaPageSettingsSelect<T extends boolean = true> {
  blogNote?: T;
  pressNote?: T;
  testimonialsSectionHeading?: T;
  testimonialsSectionDescription?: T;
  testimonialsCtaHeading?: T;
  testimonialsCtaDescription?: T;
  testimonialsCtaButtonText?: T;
  photoTabTitle?: T;
  videoTabTitle?: T;
  youtubeChannelUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports-settings_select".
 */
export interface ReportsSettingsSelect<T extends boolean = true> {
  annualSectionHeading?: T;
  annualSectionDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-us-page-settings_select".
 */
export interface ContactUsPageSettingsSelect<T extends boolean = true> {
  officeHours?: T;
  website?: T;
  offices?:
    | T
    | {
        title?: T;
        address?: T;
        phone?: T;
        id?: T;
      };
  mapHeading?: T;
  mapAddress?: T;
  mapLink?: T;
  mapBackgroundImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}